// <auto-generated />
using System;
using IoT_Module_Centralization.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IoT_Module_Centralization.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250105021834_3Creation")]
    partial class _3Creation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("IoT_Module_Centralization.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("IoT_Module_Centralization.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("IoT_Module_Centralization.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("IoT_Module_Centralization.Domain.Entities.Message", b =>
                {
                    b.HasOne("IoT_Module_Centralization.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("IoT_Module_Centralization.Domain.Entities.Module", b =>
                {
                    b.OwnsOne("IoT_Module_Centralization.Domain.ValueObjects.IpAddress", "IpAddress", b1 =>
                        {
                            b1.Property<Guid>("ModuleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("IpAddress");

                            b1.HasKey("ModuleId");

                            b1.ToTable("Modules");

                            b1.WithOwner()
                                .HasForeignKey("ModuleId");
                        });

                    b.OwnsOne("IoT_Module_Centralization.Domain.ValueObjects.Port", "Port", b1 =>
                        {
                            b1.Property<Guid>("ModuleId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Port");

                            b1.HasKey("ModuleId");

                            b1.ToTable("Modules");

                            b1.WithOwner()
                                .HasForeignKey("ModuleId");
                        });

                    b.Navigation("IpAddress")
                        .IsRequired();

                    b.Navigation("Port")
                        .IsRequired();
                });

            modelBuilder.Entity("IoT_Module_Centralization.Domain.Entities.Unit", b =>
                {
                    b.HasOne("IoT_Module_Centralization.Domain.Entities.Module", "Module")
                        .WithMany("Units")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("IoT_Module_Centralization.Domain.ValueObjects.CodigoUnidad", "Code", b1 =>
                        {
                            b1.Property<Guid>("UnitId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CodigoUnidad");

                            b1.HasKey("UnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("IoT_Module_Centralization.Domain.Entities.Module", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
